import { addOns, comparisonRows, corePackages, individualProducts, managedPlans, pricingFAQs, pricingNotes } from '../data/pricing.js'

function priceHref(source, item) {
  const value = item ? `&item=${encodeURIComponent(item)}` : ''
  return `/booking/?source=${source}${value}`
}

function CommercialButton({ ArrowIcon, children, href }) {
  return <a className="button-dark commercial-button" href={href}>{children}<ArrowIcon direction="right" /></a>
}

function PricingBlock({ pricing }) {
  return <div className="commercial-price-grid"><div><span>Implementation</span><strong>{pricing.implementation}</strong></div><div><span>Managed service</span><strong>{pricing.managedService}</strong></div></div>
}

function BulletList({ items }) {
  return <ul className="commercial-bullet-list">{items.map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul>
}

function CommercialIntro({ InternalPage, title, description, children }) {
  return <InternalPage eyebrow="NOVAHAUS / Commercial Center" title={title} description={description}>{children}</InternalPage>
}

function CommercialNotes() {
  return <aside className="commercial-notes" aria-label="Pricing notes"><span>Commercial notes</span><ul>{pricingNotes.map((note) => <li key={note}>{note}</li>)}</ul></aside>
}

function IndividualProductCard({ product, ArrowIcon }) {
  return <article className="commercial-product-card"><div className="commercial-card-top"><span className="commercial-card-index">Product / {String(individualProducts.indexOf(product) + 1).padStart(2, '0')}</span><span className="commercial-card-tag">Individual solution</span></div><h2>{product.name}</h2><p className="commercial-best-for"><strong>Best for</strong>{product.bestFor}</p><PricingBlock pricing={product.pricing} /><div className="commercial-product-columns"><div><span className="commercial-mini-label">Implementation includes</span><BulletList items={product.deliverables} /></div><div><span className="commercial-mini-label">Monthly service includes</span><BulletList items={product.monthly} /></div></div><div className="commercial-card-details"><div><span>Delivery timeline</span><strong>{product.timeline}</strong></div><div><span>Scope note</span><ul>{product.scope.map((note) => <li key={note}>{note}</li>)}</ul></div></div><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('pricing-product', product.name)}>{product.cta}</CommercialButton></article>
}

function CorePackageCard({ item, ArrowIcon }) {
  return <article className={`commercial-package-card ${item.featured ? 'is-featured' : ''}`}><div className="commercial-card-top"><span className="commercial-card-index">Package / {item.name}</span>{item.featured && <span className="commercial-popular">Most Popular</span>}</div><h3>{item.name}</h3><p className="commercial-best-for"><strong>Best for</strong>{item.bestFor}</p><PricingBlock pricing={item.pricing} /><span className="commercial-mini-label">Included</span><BulletList items={item.deliverables} />{item.notIncluded.length > 0 && <><span className="commercial-mini-label commercial-not-included-label">Not included</span><ul className="commercial-not-included">{item.notIncluded.map((entry) => <li key={entry}>{entry}</li>)}</ul></>}{item.note && <p className="commercial-scope-note">{item.note}</p>}<p className="commercial-timeline"><span>Estimated delivery</span>{item.timeline}</p><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('pricing-package', item.name)}>{item.cta}</CommercialButton></article>
}

export function PricingPage({ InternalPage, SectionLabel, Reveal, ArrowIcon }) {
  return <CommercialIntro InternalPage={InternalPage} title={<>A clearer path<br /><em>to the right system.</em></>} description="NOVAHAUS combines strategy, implementation and ongoing support to help ambitious businesses build a more useful growth infrastructure."><section className="commercial-page-content commercial-pricing-page"><Reveal className="commercial-positioning"><SectionLabel number="01">Commercial model</SectionLabel><h2>One clear build.<br /><em>Ongoing intelligence.</em></h2><p>We design and implement the right system for the next stage of the business, then keep it useful through agreed managed support.</p><div className="commercial-model-grid"><div><span>01</span><h3>Implementation</h3><p>Strategy, design, configuration, development, testing, training and launch.</p></div><div><span>02</span><h3>Managed service</h3><p>Maintenance, monitoring, AI optimisation, support, updates and ongoing improvement.</p></div><div><span>03</span><h3>Third-party costs</h3><p>Domains, hosting, AI/API usage, communication providers, advertising and external subscriptions are separate unless stated.</p></div></div></Reveal><CommercialNotes /><section className="commercial-section" aria-labelledby="individual-solutions-title"><Reveal><SectionLabel number="02">Individual solutions</SectionLabel><h2 id="individual-solutions-title">Choose the capability<br /><em>you need now.</em></h2><p className="commercial-section-intro">Start with one product or use the package structure below when several systems need to work together.</p></Reveal><div className="commercial-product-grid">{individualProducts.map((product, index) => <Reveal key={product.slug} delay={index * 45}><IndividualProductCard product={product} ArrowIcon={ArrowIcon} /></Reveal>)}</div></section><section className="commercial-section" aria-labelledby="core-packages-title"><Reveal><SectionLabel number="03">Core packages</SectionLabel><h2 id="core-packages-title">The right level of<br /><em>commercial support.</em></h2><p className="commercial-section-intro">Three starting points for businesses moving from presence to connected growth operations.</p></Reveal><div className="commercial-package-grid">{corePackages.map((item, index) => <Reveal key={item.slug} delay={index * 80}><CorePackageCard item={item} ArrowIcon={ArrowIcon} /></Reveal>)}</div></section><AddOnsSection SectionLabel={SectionLabel} Reveal={Reveal} /><PricingExplanation SectionLabel={SectionLabel} Reveal={Reveal} /><FaqSection SectionLabel={SectionLabel} Reveal={Reveal} ArrowIcon={ArrowIcon} /><Reveal className="commercial-final-cta"><SectionLabel number="07">Next step</SectionLabel><h2>Find the right<br /><em>starting point.</em></h2><p>Bring the context, the friction or the next commercial priority. We will shape the scope around what is useful.</p><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('pricing-cta')}>Book Strategy Call</CommercialButton></Reveal></section></CommercialIntro>
}

function AddOnsSection({ SectionLabel, Reveal }) {
  return <section className="commercial-section commercial-addons-section" aria-labelledby="addons-title"><Reveal><SectionLabel number="04">Optional add-ons</SectionLabel><h2 id="addons-title">Add only what<br /><em>the system needs.</em></h2><p className="commercial-section-intro">Additional pages, integrations, workflows and specialist support are scoped separately so the core price stays clear.</p></Reveal><div className="commercial-addon-grid">{addOns.map((item, index) => <Reveal className="commercial-addon-card" delay={index * 35} key={item.name}><span>{String(index + 1).padStart(2, '0')}</span><h3>{item.name}</h3><strong>{item.price}</strong></Reveal>)}</div></section>
}

function PricingExplanation({ SectionLabel, Reveal }) {
  const items = [['01', 'One-time implementation fee', 'Covers discovery, design, configuration, development, setup, testing, training and launch.'], ['02', 'Monthly managed-service fee', 'Covers system monitoring, maintenance, updates, AI optimisation, support and agreed monthly improvement capacity.'], ['03', 'Third-party usage costs', 'External tools, hosting, domains, model/API usage, communication providers, advertising and external subscriptions may be billed separately.'], ['04', 'Custom work', 'Any feature or integration outside the stated scope requires a written quotation and client approval.'], ['05', 'Scope protection', 'Prices are based on stated deliverables, revision limits and agreed timelines.']]
  return <section className="commercial-section commercial-explanation-section" aria-labelledby="pricing-explanation-title"><Reveal><SectionLabel number="05">How pricing works</SectionLabel><h2 id="pricing-explanation-title">Clear scope makes<br /><em>better decisions.</em></h2></Reveal><div className="commercial-explanation-grid">{items.map(([number, title, description], index) => <Reveal className="commercial-explanation-item" delay={index * 55} key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></Reveal>)}</div></section>
}

function FaqSection({ SectionLabel, Reveal, ArrowIcon }) {
  return <section className="commercial-section commercial-faq-section" aria-labelledby="pricing-faq-title"><Reveal><SectionLabel number="06">FAQ</SectionLabel><h2 id="pricing-faq-title">Good questions<br /><em>before we scope.</em></h2></Reveal><div className="commercial-faq-list">{pricingFAQs.map(([question, answer], index) => <Reveal className="commercial-faq-item" delay={index * 25} key={question}><details><summary>{question}<span className="faq-plus" aria-hidden="true" /></summary><p>{answer}</p></details></Reveal>)}</div><div className="commercial-faq-cta"><span>Still deciding?</span><a className="text-link" href={priceHref('pricing-faq')}>Book a Strategy Call <ArrowIcon direction="right" /></a></div></section>
}

export function ComparePlansPage({ InternalPage, SectionLabel, Reveal, ArrowIcon }) {
  return <CommercialIntro InternalPage={InternalPage} title={<>Compare the<br /><em>growth paths.</em></>} description="See what changes as your business moves from a focused launch to a connected growth system or a custom enterprise build."><section className="commercial-page-content commercial-compare-page"><Reveal className="commercial-compare-intro"><SectionLabel number="01">Compare plans</SectionLabel><h2>Start where the<br /><em>business is now.</em></h2><p>Every package is a starting point. The right choice depends on the systems, markets and operating context that matter most.</p></Reveal><div className="commercial-table-wrap" role="region" aria-label="NOVAHAUS plan comparison" tabIndex="0"><table className="commercial-comparison-table"><caption>Comparison of NOVAHAUS Launch, Growth and Enterprise packages</caption><thead><tr><th scope="col">Capability</th><th scope="col">Launch</th><th scope="col">Growth</th><th scope="col">Enterprise</th></tr></thead><tbody>{comparisonRows.map(([feature, launch, growth, enterprise]) => <tr key={feature}><th scope="row">{feature}</th><td>{launch}</td><td className={feature === 'Growth' ? 'is-highlighted' : ''}>{growth}</td><td>{enterprise}</td></tr>)}</tbody></table></div><div className="commercial-comparison-cards">{corePackages.map((item, index) => <Reveal className={`commercial-comparison-card ${item.featured ? 'is-featured' : ''}`} delay={index * 80} key={item.slug}><span>{item.featured ? 'Most Popular' : item.name}</span><h2>{item.name}</h2><PricingBlock pricing={item.pricing} /><p>{item.bestFor}</p><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('compare-plans', item.name)}>Book Strategy Call</CommercialButton></Reveal>)}</div><Reveal className="commercial-compare-note"><p>All prices are starting points. Custom integrations, third-party platform costs and requirements outside the stated scope are assessed separately.</p><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('compare-plans-cta')}>Book Strategy Call</CommercialButton></Reveal></section></CommercialIntro>
}

export function ManagedAiGrowthPage({ InternalPage, SectionLabel, Reveal, ArrowIcon }) {
  return <CommercialIntro InternalPage={InternalPage} title={<>Keep the system<br /><em>moving forward.</em></>} description="Managed AI Growth keeps the systems behind the business monitored, maintained and improved after implementation."><section className="commercial-page-content commercial-managed-page"><Reveal className="commercial-managed-intro"><SectionLabel number="01">Managed AI Growth</SectionLabel><h2>Support that stays<br /><em>close to the signal.</em></h2><p>These recurring-service tiers can follow implementation or support an eligible existing system. Each tier has a defined allowance and fair-use boundary.</p></Reveal><div className="commercial-managed-grid">{managedPlans.map((plan, index) => <Reveal className={`commercial-managed-card ${index === 1 ? 'is-featured' : ''}`} delay={index * 80} key={plan.slug}><div className="commercial-card-top"><span className="commercial-card-index">Managed plan / {String(index + 1).padStart(2, '0')}</span>{index === 1 && <span className="commercial-popular">Recommended</span>}</div><h2>{plan.name}</h2><strong className="commercial-managed-price">{plan.price}</strong><p className="commercial-best-for"><strong>Best for</strong>{plan.bestFor}</p><BulletList items={plan.features} /><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('managed-ai-growth', plan.name)}>Book Strategy Call</CommercialButton></Reveal>)}</div><Reveal className="commercial-managed-boundary"><SectionLabel number="02">Service boundary</SectionLabel><h2>Defined capacity.<br /><em>Useful continuity.</em></h2><p>Managed service is not unlimited work. Service-hour allowances, fair-use terms, response expectations and whether hours roll over are confirmed in the signed agreement. Unused service hours do not automatically roll over unless stated.</p></Reveal><Reveal className="commercial-final-cta"><SectionLabel number="03">Next step</SectionLabel><h2>Keep the next<br /><em>improvement visible.</em></h2><p>Book a Strategy Call to review the system you have, the friction you are seeing and the level of support that makes sense.</p><CommercialButton ArrowIcon={ArrowIcon} href={priceHref('managed-cta')}>Book Strategy Call</CommercialButton></Reveal></section></CommercialIntro>
}
