import { commercialKnowledge } from '../data/commercialKnowledge.js'

function DeliverySystemPage({ InternalPage, SectionLabel, Reveal, ArrowIcon }) {
  const stages = commercialKnowledge.deliveryFramework

  return <InternalPage eyebrow="NOVAHAUS / Delivery System" title={<>How Your Overseas<br /><em>Growth Team Works.</em></>} description="A clear business delivery framework from first conversation to long-term operations, with structured collaboration and professional review at every stage."><section className="delivery-system-page" aria-label="How Your Overseas Growth Team Works">
    <Reveal className="delivery-system-intro"><SectionLabel number="01">The delivery promise</SectionLabel><h2>One accountable rhythm<br /><em>from brief to operation.</em></h2><p>NOVAHAUS makes the work visible from the first conversation onward. You know what happens next, what you receive, what we own and what you need to confirm.</p><div className="delivery-system-intro-actions"><a className="button-dark" href="/booking/?source=delivery-system">Book Strategy Call <ArrowIcon direction="right" /></a><a className="text-link" href="/china-to-global/">Explore China-to-Global support <ArrowIcon direction="right" /></a></div></Reveal>
    <section className="delivery-system-timeline-section" aria-labelledby="delivery-system-timeline-title"><Reveal><SectionLabel number="02">The six-stage model</SectionLabel><h2 id="delivery-system-timeline-title">A structured path from first conversation<br /><em>to continuous optimisation.</em></h2><p>Each stage closes with a clear decision, review point or approved next step. The model supports both focused implementation and ongoing collaboration.</p></Reveal><div className="delivery-system-timeline">{stages.map((stage, index) => <Reveal className="delivery-system-stage" key={stage.number} delay={index * 60}><div className="delivery-system-stage-marker"><span>{stage.number}</span></div><h3>{stage.title}</h3><div className="delivery-system-stage-detail"><strong>What happens</strong><p>{stage.whatHappens}</p></div><div className="delivery-system-stage-detail"><strong>What you receive</strong><p>{stage.clientReceives}</p></div><div className="delivery-system-stage-detail"><strong>Our responsibility</strong><p>{stage.novaHausResponsible}</p></div><div className="delivery-system-stage-detail"><strong>You confirm</strong><p>{stage.clientConfirms}</p></div></Reveal>)}</div></section>
    <Reveal className="delivery-system-partnership"><SectionLabel number="03">The working relationship</SectionLabel><h2>Structured delivery.<br /><em>Long-term partnership.</em></h2><div className="delivery-system-partnership-grid"><div><span>01</span><h3>Visible progress</h3><p>Decisions, inputs, review points and next steps stay clear throughout the engagement.</p></div><div><span>02</span><h3>Professional review</h3><p>Important work is checked for accuracy, context, reputation and the responsibilities agreed with the client.</p></div><div><span>03</span><h3>Ongoing collaboration</h3><p>After launch, the operating rhythm can continue through defined priorities, capacity and improvement cycles.</p></div></div></Reveal>
    <Reveal className="delivery-system-final"><SectionLabel number="04">Next step</SectionLabel><h2>Bring the context.<br /><em>We will shape the path.</em></h2><p>Start with the business, market or operating burden that needs attention. The first conversation is used to understand fit, scope, timing and responsibilities.</p><a className="button-dark" href="/booking/?source=delivery-system-final">Book Strategy Call <ArrowIcon direction="right" /></a></Reveal>
  </section></InternalPage>
}

export default DeliverySystemPage
