import { valueProposition } from '../data/valueProposition.js'

function ValueLabel({ children, number }) {
  return <p className="section-label"><span className="section-label-line" />{number && <span>{number}</span>}<span>{children}</span></p>
}

export default function ValuePropositionPage({ InternalPage }) {
  return <InternalPage eyebrow="NOVAHAUS / Value Proposition" title={<>Make the next move<br /><em>more useful.</em></>} description="A clear view of what NOVAHAUS does, why the work matters and where it creates practical value for ambitious businesses."><section className="trust-center-content" aria-label="NOVAHAUS Value Proposition Center">
    <section className="trust-section" aria-labelledby="value-positioning-title"><ValueLabel number="01">Positioning statement</ValueLabel><div className="trust-responsibility-card" style={{ marginTop: '42px' }}><h2 id="value-positioning-title">{valueProposition.positioning}</h2></div></section>
    <section className="trust-section" aria-labelledby="value-elevator-title"><ValueLabel number="02">Elevator pitches</ValueLabel><h2 id="value-elevator-title">Say it clearly.<br /><em>At every altitude.</em></h2><div className="strategy-process-grid">{valueProposition.elevatorPitches.map((pitch, index) => <article className="strategy-process-step" key={pitch.label}><span>{pitch.label}</span><h3>{pitch.title}</h3><p>{pitch.copy}</p></article>)}</div></section>
    <section className="trust-section" aria-labelledby="value-why-title"><ValueLabel number="03">Why NOVAHAUS</ValueLabel><h2 id="value-why-title">The case for<br /><em>useful change.</em></h2><div className="products-comparison-grid">{valueProposition.why.map((item) => <article className="products-comparison-column" key={item.title}><span>{item.title}</span><p style={{ marginTop: '46px', color: 'var(--color-muted)', fontSize: '14px', lineHeight: '1.65' }}>{item.copy}</p></article>)}</div></section>
    <section className="trust-section" aria-labelledby="value-transformation-title"><ValueLabel number="04">Before and after</ValueLabel><h2 id="value-transformation-title">From scattered effort<br /><em>to visible leverage.</em></h2><div className="products-comparison-grid">{valueProposition.transformation.map((item) => <article className="products-comparison-column" key={item.before}><span>Before</span><p style={{ marginTop: '24px', color: 'var(--color-muted)', fontSize: '14px', lineHeight: '1.65' }}>{item.before}</p><strong style={{ color: 'var(--color-gold)' }}>After</strong><p style={{ marginTop: '17px', color: 'var(--color-ink)', fontSize: '14px', lineHeight: '1.65' }}>{item.after}</p></article>)}</div></section>
    <section className="trust-section" aria-labelledby="value-journey-title"><ValueLabel number="05">Customer transformation</ValueLabel><h2 id="value-journey-title">A better route from<br /><em>signal to system.</em></h2><div className="trust-process-grid">{valueProposition.journey.map((step) => <article className="trust-process-step" key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
    <section className="trust-section" aria-labelledby="value-competitive-title"><ValueLabel number="06">Competitive positioning</ValueLabel><h2 id="value-competitive-title">Not another isolated<br /><em>digital service.</em></h2><div className="products-comparison-grid">{valueProposition.competitive.map((item) => <article className="products-comparison-column" key={item.title}><span>{item.title}</span><p style={{ marginTop: '46px', color: 'var(--color-muted)', fontSize: '14px', lineHeight: '1.65' }}>{item.difference}</p></article>)}</div></section>
    <section className="trust-section trust-faq-section" aria-labelledby="value-objections-title"><ValueLabel number="07">Objections, answered</ValueLabel><h2 id="value-objections-title">Clear answers<br /><em>without the hard sell.</em></h2><div className="trust-faq-list">{valueProposition.objections.map((item) => <details className="trust-faq-item" key={item.question}><summary>{item.question}<span className="faq-plus" aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></section>
    <section className="trust-final-cta"><ValueLabel number="08">Next step</ValueLabel><h2>Clarity first.<br /><em>Then the right system.</em></h2><p>Start with a focused conversation about the business decision in front of you.</p><a href="/booking/?source=value-proposition" className="button-dark">Book a Strategy Call <span aria-hidden="true">↗</span></a></section>
  </section></InternalPage>
}
